[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/result"
  to = "/result"
  status = 200

[[redirects]]
  from = "/compatibility"
  to = "/compatibility"
  status = 200